name: Build and Package Executables

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: windows-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64 
          - os: macos-13
            arch: x86_64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Cache PyInstaller build folder
      uses: actions/cache@v4
      with:
        path: build
        key: pyinstaller-build-${{ runner.os }}-${{ matrix.arch }}-${{ github.sha }}
        restore-keys: |
          pyinstaller-build-${{ runner.os }}-${{ matrix.arch }}-
  
    - name: Build CLI Executable
      run: pyinstaller cli.spec

    - name: Build GUI Executable
      run: pyinstaller gui.spec

    - name: Upload CLI Executable
      uses: actions/upload-artifact@v4
      with:
        name: cli-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/cli*  # exe 또는 binary

    - name: Upload GUI Executable
      uses: actions/upload-artifact@v4
      with:
        name: gui-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/gui*
