name: Build and Package Pyz

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: |
          3.11
          3.13
          3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build CLI
      run: python build.py cli build/cli-${{ runner.os }}.pyz

    - name: Build GUI
      run: python build.py gui build/gui-${{ runner.os }}.pyz

    - name: Upload CLI Pyz
      uses: actions/upload-artifact@v4
      with:
        name: cli-${{ runner.os }}.pyz
        path: build/cli-${{ runner.os }}.pyz

    - name: Upload GUI Pyz
      uses: actions/upload-artifact@v4
      with:
        name: gui-${{ runner.os }}.pyz
        path: build/gui-${{ runner.os }}.pyz